module.exports = {
  env: {
    "BASE_URL": BASE_URL,
    "MONGO_URL": MONGO_URL,
    "ACCESS_TOKEN_SECRET": ACCESS_TOKEN_SECRET,
    "REFRESH_TOKEN_SECRET": REFRESH_TOKEN_SECRET,
    "PAYPAL_CLIENT_ID": PAYPAL_CLIENT_ID,
    "CLOUD_UPDATE_PRESET": CLOUD_UPDATE_PRESET,
    "CLOUD_NAME": CLOUD_NAME,
    "CLOUD_API": CLOUD_API
  }
}